import {
  buildBootstrapLayoutJson,
  type OfficeTableLayoutMap,
} from "./office-table-layout-shared";

function buildOfficeTableLayoutBootstrapScript(layouts: OfficeTableLayoutMap) {
  const layoutsJson = buildBootstrapLayoutJson(layouts);

  return [
    "(function(){",
    `var layouts=${layoutsJson};`,
    'if(!layouts||typeof layouts!=="object"){return;}',
    "var minimumColumnWidth=72;",
    "var gridTableSelector=\".office-dashboard-transactions-head, .office-dashboard-transactions-row, .office-pipeline-table-head, .office-pipeline-row, .office-agents-roster-head, .office-agents-roster-row, .office-agents-team-table-head, .office-agents-team-table-row, .office-list-table-header[class*='office-list-table-header-'], .office-list-table-row[class*='office-list-table-row-'], .office-table-header[class*='office-table-row-'], .office-table-row[class*='office-table-row-']\";",
    "var gridHeaderSelector=\".office-dashboard-transactions-head, .office-pipeline-table-head, .office-agents-roster-head, .office-agents-team-table-head, .office-list-table-header[class*='office-list-table-header-'], .office-table-header[class*='office-table-row-']\";",
    'function sanitizeToken(value){return String(value||"").replace(/\\s+/g," ").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}',
    'function getHeaderText(node){return node&&node.textContent?node.textContent.replace(/\\s+/g," ").trim():"";}',
    'function getColumnKey(cell,index){var explicitKey=cell&&cell.getAttribute?cell.getAttribute("data-office-column-key"):null;var normalizedExplicit=sanitizeToken(explicitKey);if(normalizedExplicit){return normalizedExplicit;}var labelKey=sanitizeToken(getHeaderText(cell));if(labelKey){return labelKey;}var classList=cell&&cell.classList?cell.classList:[];for(var classIndex=0;classIndex<classList.length;classIndex+=1){var className=classList[classIndex];if(className.indexOf("office-")===0&&!/-status-badge$/.test(className)&&!/badge$/.test(className)){return sanitizeToken(className);}}return "column-"+(index+1);}',
    "function hashColumnKeys(columnKeys){var hash=5381;for(var keyIndex=0;keyIndex<columnKeys.length;keyIndex+=1){var key=columnKeys[keyIndex];for(var charIndex=0;charIndex<key.length;charIndex+=1){hash=(((hash<<5)+hash)^key.charCodeAt(charIndex))>>>0;}hash=(((hash<<5)+hash)^31)>>>0;}return hash.toString(36);}",
    'function buildTableKey(baseKey,columnKeys){return baseKey+":sig-"+hashColumnKeys(columnKeys);}',
    'function getLegacyKeys(key){var baseKey=key.replace(/:sig-[a-z0-9]+$/,"");return baseKey===key?[]:[baseKey];}',
    "function normalizeWidth(width){var normalized=Math.round(Number(width)||0);return normalized<minimumColumnWidth?minimumColumnWidth:normalized;}",
    'function buildGridTemplate(columns){var parts=[];for(var index=0;index<columns.length;index+=1){parts.push(normalizeWidth(columns[index].width)+"px");}return parts.join(" ");}',
    "function buildTotalWidth(columns){var totalWidth=0;for(var index=0;index<columns.length;index+=1){totalWidth+=normalizeWidth(columns[index].width);}return totalWidth;}",
    "function measureColumns(cells){var measured=[];for(var index=0;index<cells.length;index+=1){measured.push({key:getColumnKey(cells[index],index),width:Math.max(Math.round(cells[index].getBoundingClientRect().width),minimumColumnWidth)});}return measured;}",
    "function resolveColumns(cells,persisted){var measured=measureColumns(cells);if(!persisted||!persisted.length){return measured;}var persistedByKey={};for(var index=0;index<persisted.length;index+=1){persistedByKey[persisted[index].key]=persisted[index].width;}for(var measuredIndex=0;measuredIndex<measured.length;measuredIndex+=1){var measuredColumn=measured[measuredIndex];measuredColumn.width=Math.max(Math.round(persistedByKey[measuredColumn.key]||measuredColumn.width),minimumColumnWidth);}return measured;}",
    'function applyGridColumns(elements,columns){var gridTemplateColumns=buildGridTemplate(columns);var totalWidth=buildTotalWidth(columns);for(var index=0;index<elements.length;index+=1){elements[index].style.gridTemplateColumns=gridTemplateColumns;elements[index].style.minWidth=totalWidth+"px";}}',
    'function syncNativeColGroup(table,columns){var colGroup=table.querySelector("colgroup[data-office-table-layout=\'true\']");if(!colGroup){colGroup=document.createElement("colgroup");colGroup.setAttribute("data-office-table-layout","true");table.insertBefore(colGroup,table.firstChild);}while(colGroup.children.length>columns.length){colGroup.removeChild(colGroup.lastChild);}while(colGroup.children.length<columns.length){colGroup.appendChild(document.createElement("col"));}for(var index=0;index<colGroup.children.length;index+=1){var columnNode=colGroup.children[index];var width=(columns[index]?normalizeWidth(columns[index].width):minimumColumnWidth)+"px";columnNode.style.width=width;columnNode.style.minWidth=width;columnNode.style.maxWidth=width;}var totalWidth=buildTotalWidth(columns);table.style.tableLayout="fixed";table.style.width=totalWidth+"px";table.style.minWidth=totalWidth+"px";}',
    "function applyNativeColumns(tables,columns){for(var index=0;index<tables.length;index+=1){syncNativeColGroup(tables[index],columns);}}",
    "function isGridHeaderRow(element){return !!(element&&element.matches&&element.matches(gridHeaderSelector));}",
    'function deriveGridTableKey(element){var classList=element&&element.classList?element.classList:[];for(var index=0;index<classList.length;index+=1){var className=classList[index];var listMatch=className.match(/^office-list-table-(?:header|row)-(.+)$/);if(listMatch){return "grid:office-list-table:"+listMatch[1];}var tableRowMatch=className.match(/^office-table-row-(.+)$/);if(tableRowMatch){return "grid:office-table-row:"+tableRowMatch[1];}if(className==="office-dashboard-transactions-head"||className==="office-dashboard-transactions-row"){return "grid:office-dashboard-transactions";}if(className==="office-pipeline-table-head"||className==="office-pipeline-row"){return "grid:office-pipeline";}if(className==="office-agents-roster-head"||className==="office-agents-roster-row"){return "grid:office-agents-roster";}if(className==="office-agents-team-table-head"||className==="office-agents-team-table-row"){return "grid:office-agents-team-table";}}return null;}',
    'function deriveNativeTableKey(table){var classList=table&&table.classList?table.classList:[];for(var index=0;index<classList.length;index+=1){if(/^(office|bm)-.*table/.test(classList[index])){return "native:"+classList[index];}}return null;}',
    'function getGridContainer(element){return element.closest(".office-data-table, .office-table")||element.parentNode||element;}',
    "var containerIdSeed=0;",
    'function getContainerId(container){if(!container.__officeTableLayoutBootstrapId){containerIdSeed+=1;container.__officeTableLayoutBootstrapId="office-table-layout-"+containerIdSeed;}return container.__officeTableLayoutBootstrapId;}',
    "function getLayoutForKeys(keys){for(var index=0;index<keys.length;index+=1){var layout=layouts[keys[index]];if(layout&&layout.length){return layout;}}return null;}",
    "var scopedGridGroups={};",
    "var gridElements=document.querySelectorAll(gridTableSelector);",
    'for(var gridIndex=0;gridIndex<gridElements.length;gridIndex+=1){var element=gridElements[gridIndex];var baseKey=deriveGridTableKey(element);if(!baseKey){continue;}var scopeKey=baseKey+"@@"+getContainerId(getGridContainer(element));var existingGridGroup=scopedGridGroups[scopeKey];if(!existingGridGroup){existingGridGroup=scopedGridGroups[scopeKey]={baseKey:baseKey,headerRows:[],elements:[]};}existingGridGroup.elements.push(element);if(isGridHeaderRow(element)){existingGridGroup.headerRows.push(element);}}',
    "var scopedNativeGroups={};",
    'var nativeTables=document.querySelectorAll("table[class]");',
    'for(var tableIndex=0;tableIndex<nativeTables.length;tableIndex+=1){var table=nativeTables[tableIndex];var nativeBaseKey=deriveNativeTableKey(table);var headerRow=table.tHead&&table.tHead.rows?table.tHead.rows.item(0):null;if(!nativeBaseKey||!headerRow){continue;}var nativeScopeKey=nativeBaseKey+"@@"+getContainerId(table);var existingNativeGroup=scopedNativeGroups[nativeScopeKey];if(!existingNativeGroup){existingNativeGroup=scopedNativeGroups[nativeScopeKey]={baseKey:nativeBaseKey,headerRows:[],tables:[]};}existingNativeGroup.headerRows.push(headerRow);existingNativeGroup.tables.push(table);}',
    "for(var scopedGridKey in scopedGridGroups){if(!Object.prototype.hasOwnProperty.call(scopedGridGroups,scopedGridKey)){continue;}var gridGroup=scopedGridGroups[scopedGridKey];var gridHeader=gridGroup.headerRows[0];if(!gridHeader){continue;}var gridHeaderCells=[];for(var gridCellIndex=0;gridCellIndex<gridHeader.children.length;gridCellIndex+=1){var gridCell=gridHeader.children[gridCellIndex];if(gridCell&&gridCell.nodeType===1){gridHeaderCells.push(gridCell);}}var gridColumnKeys=[];for(var gridKeyIndex=0;gridKeyIndex<gridHeaderCells.length;gridKeyIndex+=1){gridColumnKeys.push(getColumnKey(gridHeaderCells[gridKeyIndex],gridKeyIndex));}var gridKey=buildTableKey(gridGroup.baseKey,gridColumnKeys);var gridLayout=getLayoutForKeys([gridKey].concat(getLegacyKeys(gridKey)));if(!gridLayout){continue;}applyGridColumns(gridGroup.elements,resolveColumns(gridHeaderCells,gridLayout));}",
    "for(var scopedNativeKey in scopedNativeGroups){if(!Object.prototype.hasOwnProperty.call(scopedNativeGroups,scopedNativeKey)){continue;}var nativeGroup=scopedNativeGroups[scopedNativeKey];var nativeHeader=nativeGroup.headerRows[0];if(!nativeHeader){continue;}var nativeHeaderCells=[];for(var nativeCellIndex=0;nativeCellIndex<nativeHeader.cells.length;nativeCellIndex+=1){var nativeCell=nativeHeader.cells.item(nativeCellIndex);if(nativeCell){nativeHeaderCells.push(nativeCell);}}var nativeColumnKeys=[];for(var nativeKeyIndex=0;nativeKeyIndex<nativeHeaderCells.length;nativeKeyIndex+=1){nativeColumnKeys.push(getColumnKey(nativeHeaderCells[nativeKeyIndex],nativeKeyIndex));}var nativeKey=buildTableKey(nativeGroup.baseKey,nativeColumnKeys);var nativeLayout=getLayoutForKeys([nativeKey].concat(getLegacyKeys(nativeKey)));if(!nativeLayout){continue;}applyNativeColumns(nativeGroup.tables,resolveColumns(nativeHeaderCells,nativeLayout));}",
    "})();",
  ].join("");
}

export { buildOfficeTableLayoutBootstrapScript };
